In [1]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print("importing is done")

importing is done


In [2]:
#load the dataset
df=pd.read_csv("Diabetes Classification.csv")

In [3]:
# summarizing the dataset
df

Age  Gender  BMI Blood Pressure  FBS  HbA1c Family History of Diabetes  \
0     45    Male   25         Normal  100    5.7                         No   
1     55  Female   30           High  120    6.4                        Yes   
2     65    Male   35           High  140    7.1                        Yes   
3     75  Female   40           High  160    7.8                        Yes   
4     40    Male   20         Normal   80    5.0                         No   
..   ...     ...  ...            ...  ...    ...                        ...   
123   17  Female   15         Normal  100    5.7                         No   
124   22    Male   19         Normal  120    6.4                         No   
125   27  Female   24           High  140    7.1                         No   
126   32    Male   29           High  160    7.8                         No   
127   37  Female   34           High  180    8.5                         No   

    Smoking     Diet Exercise Diagnosis  
0        No  Healthy  Regular        No  
1       Yes     Poor       No       Yes  
2       Yes     Poor       No       Yes  
3       Yes     Poor       No       Yes  
4        No  Healthy  Regular        No  
..      ...      ...      ...       ...  
123     Yes     Poor       No       Yes  
124     Yes     Poor       No       Yes  
125     Yes     Poor       No       Yes  
126     Yes     Poor       No       Yes  
127     Yes     Poor       No       Yes  

[128 rows x 11 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Age                         128 non-null    int64  
 1   Gender                      128 non-null    object 
 2   BMI                         128 non-null    int64  
 3   Blood Pressure              128 non-null    object 
 4   FBS                         128 non-null    int64  
 5   HbA1c                       128 non-null    float64
 6   Family History of Diabetes  128 non-null    object 
 7   Smoking                     128 non-null    object 
 8   Diet                        128 non-null    object 
 9   Exercise                    128 non-null    object 
 10  Diagnosis                   128 non-null    object 
dtypes: float64(1), int64(3), object(7)
memory usage: 11.1+ KB


In [6]:
df.describe()

Age         BMI         FBS       HbA1c
count  128.000000  128.000000  128.000000  128.000000
mean    42.031250   35.359375  162.500000    7.887500
std     16.783915   14.981739   61.323975    2.146339
min     12.000000   10.000000   80.000000    5.000000
25%     28.000000   24.000000  120.000000    6.400000
50%     40.000000   34.000000  160.000000    7.800000
75%     55.000000   45.500000  205.000000    9.375000
max     75.000000   67.000000  280.000000   12.000000

In [8]:
len(df)

128

In [7]:
df.dtypes

Age                             int64
Gender                         object
BMI                             int64
Blood Pressure                 object
FBS                             int64
HbA1c                         float64
Family History of Diabetes     object
Smoking                        object
Diet                           object
Exercise                       object
Diagnosis                      object
dtype: object

In [ ]:
# we have many values as object which we have to convert to string 

In [9]:
# pre-processing the dataset
# first we check for null values
df.isnull().sum()

Age                           0
Gender                        0
BMI                           0
Blood Pressure                0
FBS                           0
HbA1c                         0
Family History of Diabetes    0
Smoking                       0
Diet                          0
Exercise                      0
Diagnosis                     0
dtype: int64

In [10]:
# we also perform the max function to confirm there are no null values
df.isnull().sum().max()

0

In [11]:
# we import new libraries to encode the columns with value as object
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder

In [12]:
label = LabelEncoder()
label

LabelEncoder()

In [13]:
# List of columns to encode
columns_to_encode = ['Gender', 'Blood Pressure', 'Family History of Diabetes','Smoking','Diet','Exercise','Diagnosis']

In [14]:
# Apply label encoding to each column to be encoded
df[columns_to_encode] = df[columns_to_encode].apply(LabelEncoder().fit_transform)

In [15]:
#this is the final dataset with all integer values
df

Age  Gender  BMI  Blood Pressure  FBS  HbA1c  Family History of Diabetes  \
0     45       1   25               2  100    5.7                           0   
1     55       0   30               0  120    6.4                           1   
2     65       1   35               0  140    7.1                           1   
3     75       0   40               0  160    7.8                           1   
4     40       1   20               2   80    5.0                           0   
..   ...     ...  ...             ...  ...    ...                         ...   
123   17       0   15               2  100    5.7                           0   
124   22       1   19               2  120    6.4                           0   
125   27       0   24               0  140    7.1                           0   
126   32       1   29               0  160    7.8                           0   
127   37       0   34               0  180    8.5                           0   

     Smoking  Diet  Exercise  Diagnosis  
0          0     0         1          0  
1          1     1         0          1  
2          1     1         0          1  
3          1     1         0          1  
4          0     0         1          0  
..       ...   ...       ...        ...  
123        1     1         0          1  
124        1     1         0          1  
125        1     1         0          1  
126        1     1         0          1  
127        1     1         0          1  

[128 rows x 11 columns]

In [24]:
# we confrm the type of value of the Gender column
type(df.Gender)

pandas.core.series.Series

In [25]:
# Now we create x (input) and y (output) variable
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [26]:
x

array([[45.,  1., 25., ...,  0.,  0.,  1.],
       [55.,  0., 30., ...,  1.,  1.,  0.],
       [65.,  1., 35., ...,  1.,  1.,  0.],
       ...,
       [27.,  0., 24., ...,  1.,  1.,  0.],
       [32.,  1., 29., ...,  1.,  1.,  0.],
       [37.,  0., 34., ...,  1.,  1.,  0.]])

In [27]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [28]:
# now we import additionl required libraries
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report
print("importing is done")

importing is done


In [29]:
# now we create training and testing dataset
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [30]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((102, 10), (26, 10), (102,), (26,))

In [31]:
# Now we create a model for our dataset
model_diab = GradientBoostingClassifier()
model_diab

GradientBoostingClassifier()

In [32]:
# we fit the training data in our model
model_diab.fit(x_train,y_train)
model_diab

GradientBoostingClassifier()

In [33]:
# Now testing new Model prediction by providing Test Data set
y_diab = model_diab.predict(x_test)

In [34]:
# this is our variable which has learned the test data
y_diab

array([0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0])

In [35]:
# Compare predictions with testing data given
# this will only give accuracy
accuracy = accuracy_score(y_test, y_diab)
np.round(accuracy,2)*100

100.0

In [37]:
# Generate a detailed classification report
report = classification_report(y_test, y_diab)
print(report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       1.00      1.00      1.00         6

    accuracy                           1.00        26
   macro avg       1.00      1.00      1.00        26
weighted avg       1.00      1.00      1.00        26



In [38]:
# we get 100% accuracy by keeping split as 80/20.
# if we keep split as 70/30
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.3,random_state=42)
model_diab = GradientBoostingClassifier()
model_diab.fit(x_train,y_train)
y_diab = model_diab.predict(x_test)
accuracy = accuracy_score(y_test, y_diab)
np.round(accuracy,2)*100

100.0

In [39]:
# Predicting the output of single test data using our trained model
y_test

array([0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0])

In [46]:
x_test[1]

array([ 35. ,   1. ,  25. ,   2. , 120. ,   6.4,   0. ,   1. ,   1. ,
         0. ])

In [47]:
x_test[1].shape

(10,)

In [48]:
x_test[1].reshape(1,10)

array([[ 35. ,   1. ,  25. ,   2. , 120. ,   6.4,   0. ,   1. ,   1. ,
          0. ]])

In [49]:
x_test[1].reshape(1,10).shape

(1, 10)

In [50]:
model_diab.predict(x_test[1].reshape(1,10))

array([1])

In [51]:
y_diab[1]

1